In [5]:
First Lab using numpy !


SyntaxError: invalid syntax (2524726468.py, line 1)

In [2]:
import numpy as np

# Create a rank 2 array
array_2d = np.array([[11, 12, 13, 14],
                     [15, 16, 17, 18]])

print(array_2d)

[[11 12 13 14]
 [15 16 17 18]]


In [3]:
import numpy as np

# Create an array with 4 rows and 3 columns of zeros
array_zeros = np.zeros((4, 3))

print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# 2. Create an array of ones with 3 rows and 4 columns
array1 = np.ones((3, 4))
print(array1)

# 3. Create an array containing integers 4 to 13 inclusive
array2 = np.arange(4, 14)
print(array2)

# 4. Create an array containing [0., 1.5, 3., 4.5]
array3 = np.array([0., 1.5, 3., 4.5])
print(array3)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 4  5  6  7  8  9 10 11 12 13]
[0.  1.5 3.  4.5]


In [9]:
# 5. Create a 2 by 2 array containing '4' in each position
array4 = np.full((2, 2), 4)
print(array4)

# 6. Create matrices: i. Identity matrix of size 4
identity_matrix = np.eye(4)
print(identity_matrix)
# ii. Diagonal matrix with [10,12] as the diagonals
diagonal_matrix = np.diag([10, 12])
print(diagonal_matrix)

# 7. Create a 3 by 3 array with random floats in [0, 10]
random_floats = np.random.rand(3, 3) * 10
print(random_floats)

[[4 4]
 [4 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0]
 [ 0 12]]
[[8.26942529 9.45726251 4.29319513]
 [4.13827492 8.90273357 3.51658664]
 [8.27019502 3.19773095 6.26135321]]


In [10]:
# 8. Create a 3 by 3 array with random integers in [10, 20]
random_integers = np.random.randint(10, 21, size=(3, 3))
print(random_integers)

# SLICING ARRAYS
# Given array
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
# a. Get a subarray of the first row and first 2 columns
sub_array_a = myArray[0, :2]
print(sub_array_a)
# b. Change all elements in 1st and second row to 0
myArray[:2] = 0
print(myArray)

# 2. Create an array and reverse the order
reversed_array = np.arange(21)[::-1]
print(reversed_array)

[[17 19 18]
 [10 20 14]
 [11 18 13]]
[11 12]
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [11]:
# RESHAPING
# Given array
myArray = np.array([[11, 12, 13], [14, 15, 16]])
# Reshape the array to an array with 3 rows
reshaped_array = myArray.reshape(3, -1)
print(reshaped_array)

# MATH
# Given array
myArray = np.arange(10)
# 1. Find the square of every number in array
squared_array = np.square(myArray)
print(squared_array)
# 2. Find the square root of every number in array
sqrt_array = np.sqrt(myArray)
print(sqrt_array)
# 3. Multiply the square of each number in array with its respective square root
result_array = squared_array * sqrt_array
print(result_array)

[[11 12]
 [13 14]
 [15 16]]
[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


In [20]:
# ADDING ELEMENTS
# Given array
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
# 1. Add a new row of elements containing 20, 21 and 22
myArray = np.vstack([myArray, [20, 21, 22]])
print(myArray)
# 2. Add a new column of elements containing 30, 40 and 50
myArray = np.hstack([myArray, np.array([[30], [40], [50]])])
print(myArray)


In [21]:
# INSERTING ELEMENTS
# 1. Add 1 column of 1 to this array
myArray = np.zeros((2, 2))
myArray = np.insert(myArray, 1, 1, axis=1)
# 2. Add 2 rows of 2 to the answer from part 1
myArray = np.insert(myArray, [0, myArray.shape[0]], 2, axis=0)
# 3. Remove the last column
myArray = np.delete(myArray, -1, axis=1)
# 4. Remove the last row
myArray = np.delete(myArray, -1, axis=0)
print(myArray)

# DELETING ELEMENTS
# Given array
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
# Remove the elements from the middle column
myArray = np.delete(myArray, 1, axis=1)
print(myArray)


[[2. 2.]
 [0. 1.]
 [0. 1.]]
[[1 3]
 [4 6]
 [9 7]]


In [22]:
# TEST EXERCISE
# Replace all odd numbers with -1
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1 % 2 != 0] = -1
print(exercise_1)

# Convert a 1-D array into a 2-D array with 3 rows
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3, -1)
print(exercise_2)

# Add 202 to all the values in given array
exercise_3 = np.arange(4).reshape(2,-1) + 202
print(exercise_3)

# Generate a 1-D array of 10 random integers between 30 and 40
random_integers = np.random.randint(30, 41, size=10)
print(random_integers)

# Find the positions where x > y and x == y
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
indices_gt = np.where(x > y)
indices_eq = np.where(x == y)
print(indices_gt, indices_eq)

# Extract the first four columns of this 2-D array
exercise_6 = np.arange(100).reshape(5, -1)
extracted_columns = exercise_6[:, :4]
print(extracted_columns)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[202 203]
 [204 205]]
[34 33 36 35 38 32 33 30 35 32]
(array([1, 2, 4, 5, 6, 7, 8, 9], dtype=int64),) (array([0], dtype=int64),)
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
